
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("GOLD"),
  ("GOLD"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("BLACK");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("BLACK"),
  ("GOLD");
INSERT INTO `TypeClient` (`tipo`)
VALUES
  ("BLACK"),
  ("BLACK"),
  ("CLASSIC"),
  ("CLASSIC"),
  ("GOLD"),
  ("CLASSIC"),
  ("BLACK"),
  ("GOLD"),
  ("BLACK"),
  ("GOLD");
